
-- FIX: adicionar set_image_url à v_products_public
-- PostgreSQL exige que novas colunas em CREATE OR REPLACE VIEW sejam adicionadas ao FINAL.
-- O PostgREST seleciona por nome (não posição), então isso é transparente para o front.

CREATE OR REPLACE VIEW public.v_products_public AS
 SELECT id,
    name,
    description,
    sku,
    category_id,
    supplier_id,
    NULL::numeric AS cost_price,
    sale_price,
    stock_quantity,
    active,
    created_at,
    updated_at,
    NULL::numeric AS suggested_price,
    dimensions,
    images,
    primary_image_url,
    videos,
    allows_personalization,
    colors,
    materials,
    tags,
    meta_title,
    meta_description,
    meta_keywords,
    is_featured,
    is_new,
    is_on_sale,
    view_count,
    favorite_count,
    order_count,
    NULL::uuid AS organization_id,
    product_type,
    is_active,
    NULL::uuid AS created_by,
    NULL::uuid AS updated_by,
    sku_promo,
    short_description,
    main_category_id,
    brand,
    is_deleted,
    deleted_at,
    is_kit,
    is_bestseller,
    min_quantity,
    box_length_mm,
    box_width_mm,
    box_height_mm,
    box_weight_kg,
    has_colors,
    has_sizes,
    ean,
    gtin,
    ncm_code,
    origin_country,
    warranty_months,
    manufacturer_sku,
    last_stock_update_at,
    NULL::character varying AS supplier_reference,
    is_textil,
    has_capacity,
    combined_sizes,
    gender,
    is_stockout,
    is_online_exclusive,
    catalog_page,
    weight_g,
    length_cm,
    width_cm,
    height_cm,
    dimensions_display,
    box_length_cm,
    box_width_cm,
    box_height_cm,
    box_volume_cm3,
    box_quantity,
    box_inner_quantity,
    packing_type,
    repacking_type,
    capacities,
    NULL::timestamp with time zone AS last_sync_at,
    NULL::uuid AS last_sync_supplier_id,
    NULL::character varying AS sync_status,
    diameter_cm,
    shape_type,
    internal_height_cm,
    internal_width_cm,
    internal_length_cm,
    internal_diameter_cm,
    packaging_material,
    packaging_color,
    has_inner_cradle,
    cradle_material,
    packaging_finish,
    is_imported,
    lead_time_days,
    requires_minimum_order,
    supply_mode,
    is_thermal,
    capacity_ml,
    slug,
    ai_summary,
    key_benefits,
    use_cases,
    target_audience,
    schema_json,
    canonical_url,
    robots_meta,
    seo_score,
    seo_last_audit_at,
    seo_issues,
    og_title,
    og_description,
    og_image_url,
    description_packaging_info,
    has_optional_packaging,
    optional_packaging_ref,
    packing_classification,
    NULL::numeric AS ipi_rate,
    NULL::character varying AS tax_reference_state,
    engraving_type,
    supplier_updated_at,
    has_gift_box,
    min_order_quantity,
    ai_title,
    ai_description,
    ai_version,
    ai_generated_at,
    ai_model,
    box_image,
    repacking_classification,
    has_commercial_packaging,
    packaging_context,
    NULL::integer AS bitrix_product_id,
    novelty_detected_at,
    novelty_expires_at,
    NULL::uuid AS ncm_id,
    NULL::timestamp with time zone AS bitrix_images_synced_at,
    is_featured_expires_at,
    is_bestseller_expires_at,
    is_on_sale_expires_at,
    is_new_expires_at,
    NULL::text AS supplier_product_url,
    freight_class,
    cubic_weight,
    auto_category,
    auto_material,
    classification_confidence,
    price_updated_at,
    NULL::text AS external_id,
    price_freshness_threshold_days,
    set_image_url
   FROM products;

ALTER VIEW public.v_products_public SET (security_invoker = false);
GRANT SELECT ON public.v_products_public TO anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.v_products_public FROM anon, authenticated, public;
