-- P10: Close 141 stale cf_orphan_no_pi remediations generated by pre-P5 circular detection.
--
-- CONTEXT:
--   Gap migration 'auto_detected_migration_20260619' (applied directly to DB, not in repo)
--   created 141 cf_orphan_no_pi remediations at 2026-06-19 20:15:05 UTC.
--   It detected "CF images with no product_images owner" by querying cf_recon.cf_image —
--   the same circular source (backfill FROM product_images.verified) that P5 fixed for
--   v_cf_orphans.
--
-- WHY THESE ARE STALE:
--   All 141 have crawl_run_id IS NULL (backfill only — no CF API confirmation).
--   All 141 have no matching product_images record at all (active or inactive or deleted).
--   Without a real crawl confirming these image_ids exist in CF, we cannot:
--     1. Confirm the images are actually in CF storage
--     2. Safely delete them from CF (security rule: never delete without confirmed owner absence)
--
-- CORRECT REMEDIATION PATH:
--   After full crawl (722 pages, ~72,199 images), v_cf_orphans will re-detect genuine orphans
--   using confirmed crawl data (crawl_run_id IS NOT NULL filter from P5). Only then should
--   CF deletion be considered.
--
-- ACTION:
--   Log each closure to action_log with explicit evidence, then close.
--   Idempotent: WHERE status = 'open' guards re-runs.

INSERT INTO cf_recon.action_log
  (actor, action, image_db_id, cf_image_id, product_id,
   old_status, new_status, evidence, reversible)
SELECT
  'claude',
  'close_stale_remediation',
  NULL,
  r.cf_image_id,
  NULL,
  'remediation_open',
  'remediation_done',
  jsonb_build_object(
    'reason',           'backfill_only_circular_detection_pre_p5',
    'remediation_id',   r.id,
    'kind',             r.kind,
    'cf_image_exists',  (ci.image_id IS NOT NULL),
    'crawl_confirmed',  false,
    'action_required',  're_evaluate_after_full_crawl_v_cf_orphans',
    'migration',        '20260619140700_cf_recon_close_stale_cf_orphan_no_pi'
  ),
  false
FROM cf_recon.remediation r
LEFT JOIN cf_recon.cf_image ci ON ci.image_id = r.cf_image_id
WHERE r.kind = 'cf_orphan_no_pi'
  AND r.status = 'open';

UPDATE cf_recon.remediation
SET status = 'done'
WHERE kind = 'cf_orphan_no_pi'
  AND status = 'open';
