-- T37b-2: Convert second batch of CANDIDATE functions to SECURITY INVOKER
-- Continuation of T37b-1. Impact: completes 210 → 0 violations together with T37b-1 and T37d.

DO $$ BEGIN IF to_regprocedure('public.get_variants_by_commemorative_date(text, integer)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.get_variants_by_commemorative_date(text, integer) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.get_variants_for_commemorative_date(text, integer, boolean)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.get_variants_for_commemorative_date(text, integer, boolean) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.get_voice_command_stats(uuid, integer)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.get_voice_command_stats(uuid, integer) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.grant_mcp_full_to_user(uuid, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.grant_mcp_full_to_user(uuid, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.has_active_step_up_challenge(step_up_action)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.has_active_step_up_challenge(step_up_action) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.has_org_role(uuid, uuid, org_role)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.has_org_role(uuid, uuid, org_role) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.has_permission(uuid, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.has_permission(uuid, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.has_role(uuid, app_role)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.has_role(uuid, app_role) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.increment_kit_template_usage(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.increment_kit_template_usage(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.is_dnd_active()') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.is_dnd_active() SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.is_kit_collaborator(uuid, uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.is_kit_collaborator(uuid, uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.is_kit_owner(uuid, uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.is_kit_owner(uuid, uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.is_order_owner(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.is_order_owner(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.is_org_admin(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.is_org_admin(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.is_org_member(uuid, uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.is_org_member(uuid, uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.is_org_owner_or_admin(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.is_org_owner_or_admin(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.is_supervisor_or_above(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.is_supervisor_or_above(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.log_access_denied(text, text, text, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.log_access_denied(text, text, text, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.log_audit(text, text, text, jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.log_audit(text, text, text, jsonb) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.log_full_scope_grant(text, uuid, text, uuid, uuid, text, boolean, timestamp with time zone, inet, text, text, jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.log_full_scope_grant(text, uuid, text, uuid, uuid, text, boolean, timestamp with time zone, inet, text, text, jsonb) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.log_login_attempt(text, boolean, uuid, text, text, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.log_login_attempt(text, boolean, uuid, text, text, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.log_rls_denial(text, text, text, text, uuid, uuid, text, text, text, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.log_rls_denial(text, text, text, text, uuid, uuid, text, text, text, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.log_step_up_audit(text, step_up_action, jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.log_step_up_audit(text, step_up_action, jsonb) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.log_user_logout()') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.log_user_logout() SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.log_voice_command(text, text, boolean, jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.log_voice_command(text, text, boolean, jsonb) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.lookup_request_id(text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.lookup_request_id(text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.magic_up_calculate_score(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.magic_up_calculate_score(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.magic_up_create_brand_kit(jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.magic_up_create_brand_kit(jsonb) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.magic_up_create_campaign(jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.magic_up_create_campaign(jsonb) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.magic_up_get_brand_kit(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.magic_up_get_brand_kit(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.magic_up_get_campaign(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.magic_up_get_campaign(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.magic_up_get_dashboard()') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.magic_up_get_dashboard() SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.magic_up_increment_metric(uuid, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.magic_up_increment_metric(uuid, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.magic_up_save_generation(jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.magic_up_save_generation(jsonb) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.mark_all_notifications_read()') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.mark_all_notifications_read() SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.mark_notification_read(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.mark_notification_read(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.mark_step_up_password_verified(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.mark_step_up_password_verified(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.mcp_audit_violation(uuid, text, jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.mcp_audit_violation(uuid, text, jsonb) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.move_favorites_to_trash(uuid[])') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.move_favorites_to_trash(uuid[]) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.ownership_repair(uuid, boolean)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.ownership_repair(uuid, boolean) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.rate_limit_check(text, text, integer, integer)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.rate_limit_check(text, text, integer, integer) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.record_app_vital(text, double precision, text, text, text, text, uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.record_app_vital(text, double precision, text, text, text, text, uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.record_auth_attempt(text, text, boolean, text, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.record_auth_attempt(text, text, boolean, text, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.record_dev_route_telemetry(text, text, text, integer)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.record_dev_route_telemetry(text, text, text, integer) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.record_mcp_access_violation(uuid, text, text, text, uuid, text, text, text, jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.record_mcp_access_violation(uuid, text, text, text, uuid, text, text, text, jsonb) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.record_platform_failure(text, text, text, integer, text, boolean, boolean, integer)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.record_platform_failure(text, text, text, integer, text, boolean, boolean, integer) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.register_ai_routing_decision(text, uuid, uuid[], uuid[], jsonb, uuid, uuid, integer, integer, text, uuid, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.register_ai_routing_decision(text, uuid, uuid[], uuid[], jsonb, uuid, uuid, integer, integer, text, uuid, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.registrar_entrada_estoque(character varying, integer, numeric, character varying, character varying, text, uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.registrar_entrada_estoque(character varying, integer, numeric, character varying, character varying, text, uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.registrar_saida_estoque(character varying, integer, character varying, character varying, text, uuid, boolean)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.registrar_saida_estoque(character varying, integer, character varying, character varying, text, uuid, boolean) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.repair_ownership_orphans(uuid, boolean, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.repair_ownership_orphans(uuid, boolean, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.request_step_up_challenge(step_up_action, text, inet, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.request_step_up_challenge(step_up_action, text, inet, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.reset_optimization_queue(boolean)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.reset_optimization_queue(boolean) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.reset_user_step_up_state(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.reset_user_step_up_state(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.restore_collection_item_from_trash(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.restore_collection_item_from_trash(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.restore_favorite_item_from_trash(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.restore_favorite_item_from_trash(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.restore_product(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.restore_product(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.revoke_all_user_tokens(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.revoke_all_user_tokens(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.revoke_mcp_full_from_user(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.revoke_mcp_full_from_user(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.revoke_user_step_up(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.revoke_user_step_up(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.rotate_mcp_key(uuid, text, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.rotate_mcp_key(uuid, text, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.search_products_semantic(text, jsonb, integer)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.search_products_semantic(text, jsonb, integer) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.search_records_rerank(text, jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.search_records_rerank(text, jsonb) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.set_connection_failure_window_minutes(integer)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.set_connection_failure_window_minutes(integer) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.set_connections_auto_test_interval(integer)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.set_connections_auto_test_interval(integer) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.soft_delete_product(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.soft_delete_product(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.soft_delete_quote(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.soft_delete_quote(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.step_up_challenge_verify(uuid, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.step_up_challenge_verify(uuid, text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.step_up_token_create(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.step_up_token_create(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.step_up_token_revoke(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.step_up_token_revoke(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.step_up_user_settings_get(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.step_up_user_settings_get(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.step_up_user_settings_set(jsonb, uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.step_up_user_settings_set(jsonb, uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.store_user_token_revocation(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.store_user_token_revocation(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.unblock_ip(text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.unblock_ip(text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.user_belongs_to_org(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.user_belongs_to_org(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.user_can_skip_step_up(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.user_can_skip_step_up(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.user_is_org_member(uuid)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.user_is_org_member(uuid) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.validate_mcp_key(text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.validate_mcp_key(text) SECURITY INVOKER'; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('public.verify_step_up_otp(uuid, text)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION public.verify_step_up_otp(uuid, text) SECURITY INVOKER'; END IF; END $$;
