-- Seed idempotente dos 32 badges (fix_version=pbd_v1_20260627).
-- ON CONFLICT DO NOTHING: reaplicacao do runner nao sobrescreve edicoes do admin.
INSERT INTO public.product_badge_definitions
  (badge_key,name,short_label,description,business_rule,category,source_kind,data_source,placements,surfaces,icon_lucide,icon_emoji,color_token,class_bg,class_text,class_border,priority,sort_order,config,supports_expiration,is_enabled)
VALUES
('stockout','Fora de estoque','Esgotado','Produto sem saldo disponível em estoque.','products.is_stockout = TRUE (equivale a stock_quantity menor ou igual a 0).','status_estoque','computed','products.is_stockout',ARRAY['card_header_right'],ARRAY['catalog','super_filter','product_detail','comparison'],'PackageX','❌','red',NULL,NULL,NULL,99,10,'{}'::jsonb,false,true),
('low_stock','Estoque baixo','Baixo','Saldo abaixo do limiar do fornecedor.','products.stock_quantity > 0 E <= suppliers.low_stock_threshold.','status_estoque','computed','products.stock_quantity vs suppliers.low_stock_threshold',ARRAY['card_header_right'],ARRAY['catalog','super_filter','product_detail'],'AlertTriangle','⚠️','orange',NULL,NULL,NULL,95,20,'{"thresholdSource":"suppliers.low_stock_threshold"}'::jsonb,false,true),
('last_units','Últimas unidades','Últ. un.','Risco alto de ruptura: estoque baixo somado a alta velocidade de venda.','mv_product_intelligence.is_stockout_risk = TRUE.','status_estoque','intelligence','mv_product_intelligence.is_stockout_risk',ARRAY['intelligence_panel','product_detail'],ARRAY['product_detail','catalog'],'AlertTriangle','⚠️','red','bg-red-50','text-red-700','border-red-200',85,30,'{}'::jsonb,false,true),
('novelty','Novidade','Novidade','Produto novo com contagem regressiva até expirar a novidade.','products.is_new = TRUE E novelty_expires_at > NOW().','novidade','pipeline','products.is_new + products.novelty_expires_at',ARRAY['card_header_left'],ARRAY['catalog','super_filter','novelties'],'Sparkles','🆕','blue',NULL,NULL,NULL,90,40,'{"expiresColumn":"novelty_expires_at","defaultWindowDays":30}'::jsonb,true,true),
('new_arrival','Novo / Lançamento','Novo','Produto recém-cadastrado sem contagem (fallback) ou flag de lançamento.','products.is_new = TRUE com novelty_expires_at nulo/expirado; ou catalogFlags.new_arrival.','novidade','computed','products.is_new (fallback) / catalogFlags.new_arrival',ARRAY['card_header_left','intelligence_panel','product_detail'],ARRAY['catalog','product_detail'],'Star','🌟','blue','bg-blue-100','text-blue-800','border-blue-200',88,50,'{}'::jsonb,false,true),
('featured','Destaque','Destaque','Produto destacado pela curadoria comercial.','products.is_featured = TRUE. Expira se is_featured_expires_at preenchido.','curadoria','manual','products.is_featured',ARRAY['card_header_left','intelligence_panel','product_detail'],ARRAY['catalog','super_filter','product_detail'],'Sparkles','⭐','purple',NULL,NULL,NULL,80,60,'{"expiresColumn":"is_featured_expires_at"}'::jsonb,true,true),
('bestseller','Mais vendido','Top','Produto marcado como mais vendido (curadoria/pipeline).','products.is_bestseller = TRUE.','curadoria','hybrid','products.is_bestseller',ARRAY['card_header_left','product_detail'],ARRAY['catalog','product_detail'],'Crown','👑','amber',NULL,NULL,NULL,78,70,'{"expiresColumn":"is_bestseller_expires_at"}'::jsonb,true,true),
('on_sale','Promoção','Promo','Produto em promoção por período determinado.','products.is_on_sale = TRUE E is_on_sale_expires_at preenchido (constraint).','comercial','pipeline','products.is_on_sale + products.is_on_sale_expires_at',ARRAY['card_header_left'],ARRAY['catalog','super_filter','product_detail'],'Tag','🏷️','green',NULL,NULL,NULL,60,80,'{"expiresColumn":"is_on_sale_expires_at","helper":"fn_set_product_on_sale"}'::jsonb,true,true),
('gift_box','Embalagem especial','Embalagem','Produto com embalagem comercial/presenteável.','products.has_gift_box = TRUE (sync com has_commercial_packaging).','comercial','computed','products.has_gift_box / has_commercial_packaging',ARRAY['card_header_left','card_body'],ARRAY['catalog','product_detail'],'Gift','🎁','teal',NULL,NULL,NULL,55,90,'{}'::jsonb,false,true),
('kit','Kit','Kit','Produto que já é um kit montado.','products.is_kit = TRUE.','atributo','manual','products.is_kit',ARRAY['card_header_left'],ARRAY['catalog','product_detail'],'Package','📦','indigo',NULL,NULL,NULL,50,100,'{}'::jsonb,false,true),
('build_kit','Monte seu Kit','Montar','Atalho para montar um kit a partir de um produto avulso.','products.is_kit = FALSE (somente não-kit). Ação de UI.','acao','ui_only','products.is_kit = false (atalho UI)',ARRAY['card_body'],ARRAY['catalog','product_detail'],'Package','🧰','amber',NULL,NULL,NULL,30,110,'{}'::jsonb,false,true),
('personalization','Personalização','Person.','Produto permite personalização/gravação de logo.','products.allows_personalization = TRUE.','acao','computed','products.allows_personalization',ARRAY['card_body'],ARRAY['catalog','product_detail'],'Palette','🎨','blue',NULL,NULL,NULL,35,120,'{}'::jsonb,false,true),
('logo_preview','Visualizar com Logo','Logo','Atalho para simular a arte com o logo do cliente.','Sem condição de banco (atalho de UI em todos os cards).','acao','ui_only','(sem condicao - atalho UI)',ARRAY['card_body'],ARRAY['catalog','product_detail'],'Sparkles','✨','green',NULL,NULL,NULL,34,130,'{}'::jsonb,false,true),
('hot_item','Hot Item','Hot','Sinalizado como Hot Item pela Inteligência Comercial (alta procura + reposição recente).','mv_product_intelligence.is_hot_product = TRUE E badge habilitada.','inteligencia','intelligence','mv_product_intelligence.is_hot_product',ARRAY['intelligence_panel','product_detail','catalog'],ARRAY['catalog','super_filter','product_detail'],'Flame','🔥','brand','bg-brand-primary-100','text-brand-primary-800','border-brand-primary-200',82,140,'{"livesIn":"admin_settings.intelligence_badges"}'::jsonb,false,true),
('best_seller','Best-seller','Best','Vende em média acima do limiar nos últimos 7 dias.','mv_stock_velocity.avg_daily_depletion_7d >= limiar configurável.','inteligencia','intelligence','mv_stock_velocity.avg_daily_depletion_7d',ARRAY['intelligence_panel','catalog'],ARRAY['catalog','super_filter','product_detail'],'Trophy','🏅','yellow','bg-yellow-100','text-yellow-800','border-yellow-200',75,150,'{"minAvgDailyDepletion7d":15,"livesIn":"admin_settings.intelligence_badges"}'::jsonb,false,true),
('emerging','Emergente','Emergente','Velocidade de venda subindo vs período anterior.','mv_stock_velocity.velocity_trend > 1.3.','inteligencia','intelligence','mv_stock_velocity.velocity_trend',ARRAY['intelligence_panel','product_detail'],ARRAY['product_detail','catalog'],'Rocket','📈','green','bg-green-100','text-green-800','border-green-200',70,160,'{"trendThreshold":1.3}'::jsonb,false,true),
('declining','Em queda','Queda','Velocidade de venda caindo vs período anterior.','mv_stock_velocity.velocity_trend < 0.7.','inteligencia','intelligence','mv_stock_velocity.velocity_trend',ARRAY['intelligence_panel','product_detail'],ARRAY['product_detail'],'TrendingDown','📉','red','bg-red-100','text-red-800','border-red-200',65,170,'{"trendThreshold":0.7}'::jsonb,false,true),
('class_a','Classe A','Classe A','Top de receita/giro no portfólio do fornecedor (classificação ABC).','mv_product_intelligence.abc_classification = A.','inteligencia','intelligence','mv_product_intelligence.abc_classification',ARRAY['intelligence_panel','product_detail'],ARRAY['product_detail'],'Trophy','🏆','purple','bg-purple-100','text-purple-800','border-purple-200',60,180,'{}'::jsonb,false,true),
('frequent_restock','Reposição freq.','Repõe','Fornecedor repõe estoque com frequência (baixo risco de ruptura).','mv_product_intelligence.has_frequent_restock = TRUE.','inteligencia','intelligence','mv_product_intelligence.has_frequent_restock',ARRAY['intelligence_panel','product_detail'],ARRAY['product_detail','catalog'],'Zap','🔄','cyan','bg-cyan-100','text-cyan-800','border-cyan-200',50,190,'{}'::jsonb,false,true),
('gender','Gênero','Gênero','Gênero alvo do produto (moda/acessórios).','products.gender IN (masculino,feminino,infantil,unissex).','atributo','computed','products.gender',ARRAY['card_body'],ARRAY['catalog','product_detail'],'Users','👥','pink',NULL,NULL,NULL,40,200,'{"enum":["masculino","feminino","infantil","unissex"]}'::jsonb,false,true),
('colors','Cores','Cores','Produto possui variantes de cor.','products.has_colors = TRUE ou products.colors não vazio.','atributo','computed','products.has_colors + products.colors',ARRAY['card_body'],ARRAY['catalog','product_detail'],'Palette','🎨','neutral',NULL,NULL,NULL,38,210,'{}'::jsonb,false,true),
('materials','Materiais','Materiais','Tags de materiais do produto.','products.materials não vazio (cache de product_materials).','atributo','computed','products.materials',ARRAY['card_body'],ARRAY['catalog','product_detail'],'Layers','🧵','stone',NULL,NULL,NULL,36,220,'{}'::jsonb,false,true),
('category','Categoria','Categoria','Categoria principal do produto.','products.category_id não nulo.','atributo','computed','products.category_id',ARRAY['card_body'],ARRAY['catalog','product_detail'],'Folder','🗂️','neutral',NULL,NULL,NULL,25,230,'{}'::jsonb,false,true),
('category_groups','Grupos','Grupos','Categorias adicionais (grupos) do produto.','product_category_assignments com is_primary = false.','atributo','computed','product_category_assignments (is_primary=false)',ARRAY['card_body'],ARRAY['catalog','product_detail'],'FolderTree','🗂️','neutral',NULL,NULL,NULL,24,240,'{}'::jsonb,false,true),
('replenishment','Reposição','Reposição','Previsão de reposição/próxima entrada de estoque.','product_variants.next_entry_date / next_entry_quantity.','atributo','computed','product_variants.next_entry_date',ARRAY['card_body'],ARRAY['catalog','product_detail','inventory'],'RefreshCw','🔄','cyan',NULL,NULL,NULL,28,250,'{}'::jsonb,false,true),
('price_freshness','Freshness de preço','Preço','Indica que o preço não é verificado há muito tempo.','products.price_last_verified_at mais antigo que price_freshness_threshold_days.','sistema','computed','products.price_last_verified_at vs price_freshness_threshold_days',ARRAY['card_body'],ARRAY['product_detail','inventory'],'Clock','🕐','orange',NULL,NULL,NULL,20,260,'{"thresholdColumn":"price_freshness_threshold_days","defaultDays":60}'::jsonb,false,true),
('sku','SKU','SKU','Código SKU do produto (sempre presente).','products.sku (cobertura 100%).','sistema','computed','products.sku',ARRAY['corner_br'],ARRAY['catalog','product_detail'],'Hash','#️⃣','neutral',NULL,NULL,NULL,15,270,'{}'::jsonb,false,true),
('ai_word_magic','IA Word Magic','IA','Conteúdo aprimorado por IA.','products.ai_version > 0.','sistema','pipeline','products.ai_version',ARRAY['corner_bl'],ARRAY['catalog','product_detail'],'Sparkles','✨','violet',NULL,NULL,NULL,18,280,'{}'::jsonb,false,true),
('sales_90d','Vendas 90d','Vendas','Volume de vendas nos últimos 90 dias (EM DESENVOLVIMENTO).','analytics.mv_product_intell (materialized view ainda não criada).','sistema','intelligence','analytics.mv_product_intell',ARRAY['card_footer'],ARRAY['catalog','product_detail'],'BarChart3','📊','neutral',NULL,NULL,NULL,10,290,'{"status":"em_desenvolvimento"}'::jsonb,false,false),
('seasonal','Sazonal','Sazonal','Produto sazonal (data/coleção específica).','products.is_seasonal = TRUE.','comercial','computed','products.is_seasonal',ARRAY['card_body'],ARRAY['catalog','product_detail'],'CalendarRange','🗓️','orange',NULL,NULL,NULL,45,300,'{}'::jsonb,false,true),
('online_exclusive','Exclusivo Online','Online','Produto exclusivo do canal online.','products.is_online_exclusive = TRUE.','comercial','computed','products.is_online_exclusive',ARRAY['card_body'],ARRAY['catalog','product_detail'],'Globe','🌐','indigo',NULL,NULL,NULL,44,310,'{}'::jsonb,false,true),
('closeout','Ponta de estoque','Ponta','Produto em liquidação/ponta de estoque.','products.is_closeout = TRUE.','comercial','computed','products.is_closeout',ARRAY['card_header_left','card_body'],ARRAY['catalog','product_detail'],'Tag','🏷️','orange',NULL,NULL,NULL,58,320,'{}'::jsonb,false,true)
ON CONFLICT (badge_key) DO NOTHING;
