-- Security note:
-- This migration intentionally performs no user-password updates.
-- Account credential resets must be executed via operational runbooks
-- (outside versioned schema migrations) using environment-scoped secrets.
